### ISSUE TITLE
Undoing `Require` does not unload Elpi commands

### ISSUE THREAD

**Issue by Blaisorblade** [LPCIC/coq-elpi#452]
Discovered on `derive` — not minimized.
Here, the syntax remains in place after stepping back; https://github.com/LPCIC/coq-elpi/issues/449 also has an issue with `Undo`, but there undoing works and redoing doesn't.

* I used `Require Import bedrock.prelude.elpi.derive.`
* added a `#[only(eq_dec)] derive some_type.` command
* dropped the `Require Import bedrock.prelude.elpi.derive.` because the `derive` statement worked anyway
* did lots of editing and stepping back and forth (in VsCoq 1)
* tried to build with `coqc`, and that failed.

With `#[only(eq_dec)] derive some_type.`:
```
File "./fmdeps/cpp2v-core/theories/lang/cpp/model/inductive_pointers.v", line 279, characters 18-24:
Error:
Syntax error: [quoted_attributes] or [vernac] expected (in [decorated_vernac]).
```

With `derive alloc_id_aux.`:
```
File "./fmdeps/cpp2v-core/theories/lang/cpp/model/inductive_pointers.v", line 279, characters 2-8:
Error: Syntax error: illegal begin of vernac.
```

**Comment by Blaisorblade** [comment]
Relatedly, a colleague has reported an unexplained `Syntax error: entry [elpi_loc] is empty.` in Proof General (fixed by restarting proof general).
In coq-lsp, I'm also seeing spurious `Syntax error: entry [elpi_loc] is empty.` in code that does not load elpi, but only if I open _other_ files that do load elpi.

**Comment by gares** [comment]
Hum, LSP wants one server for all your files... so I guess the bug leaks.
What I still don't get is what is coq-elpi specific.. there are other plugins extending the grammar...

**Comment by Blaisorblade** [comment]
oh maybe it's just https://github.com/coq/coq/issues/12575 /  https://github.com/coq/coq/pull/17069

**Comment by Blaisorblade** [comment]
Not quite — https://github.com/coq/coq/pull/17069 was [backported](https://coq.github.io/doc/v8.17/refman/changes.html#id69).

But comments there suggest plugins need changes — SkySkimmer mentions elpi needs special support since it has an evolving grammar.

**Comment by gares** [comment]
@SkySkimmer can you help me reproduce the problem and fix elpi?
I tried with `Reset Initial` but I could not get a bug.

**Comment by SkySkimmer** [comment]
I'll try to have a look next week

**Comment by SkySkimmer** [comment]
IIRC the idea is that you do `Elpi Export` of some program (or Import something that does), then backtrack (either interactively, or closing the current module), the exported syntax is still active.

**Comment by SkySkimmer** [comment]
https://github.com/LPCIC/coq-elpi/pull/463

**Comment by SkySkimmer** [comment]
>Relatedly, a colleague has reported an unexplained Syntax error: entry [elpi_loc] is empty. in Proof General (fixed by restarting proof general).

This may be a bug in the grammar engine state reset. Hard to say without reproducing.
